---
title: "matrix operations"
output: html_notebook
---

```{r}
m1<-matrix(data = c(1,2,3,4,5,6), nrow = 3, ncol = 2,byrow = TRUE)
m1
```


```{r}
```


```{r}
mr2<-rbind(c(1,2,3), c(4,5,6))
mr2
```


```{r}
#row binding
mr2<-rbind(c(10,20,30), c(4.5,5.5,6.5))
mr2
```


```{r}
#columnar binding
mc3<-cbind(c(10,20,30), c(4.5,5.5,6.5))
mc3
```


```{r}
#matrix from a vector
v1<-c(100,200,300,400)
dim(v1)<-c(2,2)
v1
```


```{r}
m1
```


```{r}
m1[ 1,2  ] #row, column
```


```{r}
#row 1 of matrix

m1[ 1,  ] #column position blank means all columns
```


```{r}

#second column from the matrix
data<-matrix(data=seq(10,200,by=10), nrow = 5)
data

data[  , 2 ] #second column will be returned as a 1 D vector
```


```{r}

#second and 4th column

data[   , c(2,4)    ] #a matrix is returned
```


```{r}
#multiple rows and columns
#return a matrix
data[ c(1,3), c(2,4)  ] #row 1 and 3, columns 2 and 4
```


```{r}
#recycling
data
paste("###########################")

# T F T F T,   T F T F
data[ c(T,F), c(T,F)  ]
```


```{r}

#negative indices
data
paste("###########################")

data[ c(-1,-2), c(-3,-4) ]
```


```{r}
#change labels for rows and columns
dimnames(data)<-list( c('r1','r2','r3','r4','r5'), c('c1','c2','c3','c4')  )
data
```


```{r}
m1<-matrix(data = c(1,2,3,4,5,6),byrow=TRUE, nrow = 2)
m1
```


```{r}
m2<-matrix(data = c(10,20,30,40,50,60),byrow=TRUE, nrow = 2)
m2
```


```{r}
m1 + m2 #add elements at corresponding positions in the 2 matrices
```


```{r}

#1 2        10 20 
#3 4        30 40
```


```{r}

m

m1 %*% m2
```


```{r}
m1<-matrix(data = c(1,2,3,4),byrow=TRUE, nrow = 2)
m2<-matrix(data = c(10,20,30,40),byrow=TRUE, nrow = 2)

```


```{r}
m1 %*% m2 #matrix multiplication
```


```{r}
dim(m1) #dimensions
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```


```{r}
```

