---
title: "vectors"
output: html_notebook
---

```{r}
v1<-c(10,20,30,40)
v1
```


```{r}

v2<-seq(10,100, by=10)
v2
```


```{r}
#index

v2[7]
```


```{r}
v2[-7] #all values except 7th position value
```


```{r}
#1st and 2nd value
v2[c(1,2)]
```


```{r}
#all values except first and second
v2[c(-1,-2)]

```


```{r}
#slicing

v2[1:4]
```


```{r}
v2[2:7]
```


```{r}
#recycling

v2[ c(T,F)  ]
```


```{r}
v2[ c(T,F,F)  ] #every second and every third element in the vector is skipped
```
        

```{r}

#print every 5th element in the sequence between 1, 100
temp<-seq(1,100,by=1)
temp[ c(F,F,F,F,T)  ]
```


```{r}
```


```{r}

#name the positions in a vector

data<-c(10,20,30,40)

names(data)<-c("first","second","third","fourth")
data
```


```{r}
data['second']
```


```{r}
#eliminate a particular index
data[ names(data)!='second'     ]

```


```{r}
#multiple values

data[ names(data) %in% c('first','third')   ]
```


```{r}
#creating vector with labels in the same line

temp<-c( first=100,second=200,third=300   )
temp
```


```{r}

temp['first']<-7890
temp
```


```{r}
#delete an object in R

temp<-NULL
rm(temp)
```


```{r}


v1<-c(1,2,3,4)
v2<-c(10,20,30,40,50,60)
v3<-c(100,200,300,400)

```
```{r}
v1 + v2 #recycling concept
```


```{r}
v1 + v3
```


```{r}
v1 - v3
v1 * v3
v1 / v3 #division
v1 %% v3 #remainder

```
```{r}
v1 * 50 #all values in v1 multiplied by 50
```


```{r}
v1
v1 + 50
```


```{r}
#creating vectors of characters

employees<-c("John","Mathew","Jacob")
employees
```


```{r}

#print square root of all values in vector v2
v2
```


```{r}
10 ** 2
```

